#application: myplay
#version: 1
runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /.*
  script: myplay.my_app
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"


