runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: myplay.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
